name: Daily Nord VPN Servers Feed

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 AM (UTC) everyday (Check https://crontab.tech/)

jobs:
  download-nordvpnservers:
    name: Download Nord VPN Servers via API
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Checkout the repo
        uses: actions/checkout@master

      - name: 🐍 Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: 🚀 Run automation script
        run: python  .script/get-nordvpnservers.py

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add nordvpn-servers.csv
          git commit -m "Adding new nord vpn server daily feed" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
